-- v12.13 - Central de integrações comerciais

INSERT IGNORE INTO settings (`key`, value) VALUES
('payment_enabled', '0'),
('payment_provider', 'mercadopago'),
('payment_sandbox', '1'),
('payment_public_key', ''),
('payment_secret_key', ''),
('payment_webhook_secret', ''),
('email_enabled', '0'),
('email_provider', 'log'),
('email_from', 'contato@caminhosdealagoas.com'),
('email_from_name', 'Caminhos de Alagoas'),
('email_api_key', ''),
('email_smtp_host', ''),
('email_smtp_port', '587'),
('email_smtp_user', ''),
('email_smtp_pass', ''),
('analytics_ga4_id', ''),
('analytics_gtm_id', ''),
('analytics_meta_pixel_id', ''),
('analytics_tiktok_pixel_id', ''),
('analytics_hotjar_id', ''),
('analytics_utmify_id', ''),
('ops_webhook_enabled', '0'),
('ops_webhook_url', ''),
('ops_webhook_secret', ''),
('whatsapp_api_enabled', '0'),
('whatsapp_phone_id', ''),
('whatsapp_token', ''),
('whatsapp_admin_phone', ''),
('production_mode', '0'),
('security_headers_enabled', '1'),
('hsts_enabled', '0'),
('backup_enabled', '0'),
('backup_path', 'C:/xampp/htdocs/caminhosdealagoas/storage/backups'),
('backup_retention_days', '30'),
('logs_retention_days', '90'),
('legal_terms_url', ''),
('legal_privacy_url', '');
